apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-nr1t
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0043-tenant/tkrw-pr712-0075-0043-app/devfile-sample-nr1t@sha256:d88d259b3bebbe009b3db13a2f7710520f2b8566b16a247cfc9dfdbd567eb097
        name: my-nodejs
        resources: {}
status: {}
